import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import {
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  Link,
  Button,
} from "@nextui-org/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main className="h-full dark">
            <Navbar isBordered>
              <NavbarContent className="hidden gap-4 sm:flex" justify="center">
                <NavbarItem>
                  <Link color="foreground" href="/">
                    Home
                  </Link>
                </NavbarItem>
                <NavbarItem>
                  <Link color="foreground" href="/partial">
                    Partial Render
                  </Link>
                </NavbarItem>
                <NavbarItem>
                  <Link color="foreground" href="/issue">
                    Issue
                  </Link>
                </NavbarItem>
              </NavbarContent>
            </Navbar>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
